### PR TITLE
Trailer Swift

### PR DESCRIPTION
**Pull request by ptsochantaris**
- Using native table views on OS X for big memory and performance wins
- All code moved to Swift
- Big codebase file & directory cleanups
- Options to filter using labels and statuses
- Lots of small bugfixes in syncing
- Improvements in label and status handling
- Using this PR as guinea pig for labels bug as well, so please don't merge

### CODE REVIEW

**Comment by mauricerkelly** [comment]
@ptsochantaris @cheba I noticed that Trailer had disappeared and [found a crash report](http://cl.ly/373h3p2V0421) for build 1166 (v1.2.0).

**Comment by cheba** [comment]
Another [Test 10 crash report](http://cl.ly/3Q1k3S1b3T1r).

**Comment by ptsochantaris** [comment]
@mauricerkelly @cheba thanks for the crash reports guys.  Will be investigating them as well as the display problems ASAP and reverting with an update soon.

**Comment by ptsochantaris** [comment]
New test build (11) - attempted to re-architect to reduce the strange callback-related issues, as well as fixing quite a few other bugs and making API calls quite a bit more efficient:

https://www.dropbox.com/s/9pm2rv0v8zh0v2q/Trailer-TEST11.zip?dl=0

**Comment by cheba** [comment]
[Crash Report](http://cl.ly/0i0X1n2r3o09) for build 11.

**Comment by ptsochantaris** [comment]
Thanks @cheba - there was a stupid regression there which would explode when the network status of the system would change, fixed it (plus some other possible minor issues)  Here is an updated build:

https://www.dropbox.com/s/uguxofhwdi43ruo/Trailer-TEST12.zip?dl=0

**Comment by ptsochantaris** [comment]
@mauricerkelly Have been looking at your compilation error - I tried removing all my Xcode instances, derived data, nuked the Developer directory in ~Library, caches, etc. but I couldn't reproduce it - Seems that contentView in NSWindow is non-optional, both on my main dev system and my laptop Xcode instances (freshly installed from the App Store).

Can you check if perhaps you don't have some older/stale Swift standard library version on your system which is causing this?  Also, the latest push removed the prefix headers to help the compiler "behave", perhaps this may help unblock things on your end?

**Comment by cheba** [comment]
A [crash report](http://cl.ly/0v3h050U1B3n) for Test 12.

**Comment by ptsochantaris** [comment]
Thanks for spotting that @cheba - I'm guessing this occurred when you selected a notification referring something that no longer existed. Have improved the code there to catch this corner case, as well as making other type casting a little safer. This crash should no longer occur in this build:

https://www.dropbox.com/s/l9g5wa0i5985vis/Trailer-TEST13.zip?dl=0

**Comment by mauricerkelly** [comment]
@ptsochantaris I’ve switched to using a 6.2 beta and it’s compiling fine. Still reporting as an optional in my 6.1 (6A1046a) install, but it’s a generated header. In ObjC the `contentView` property is defined as: `@property (strong) id /* NSView * */ contentView;` - seems to be getting generated differently on my 6.1 compared to others!

I’ll stick with 6.2 for now, as I’m working with 6.1 during the day and I can’t spare the re-install time for it right now :-(

**Comment by cheba** [comment]
[TEST13 crash report](http://cl.ly/1g2U1m2L192m)

**Comment by ptsochantaris** [comment]
New test build - have tried to work out many places where there may have been some cyclical references, that could perhaps lead to crashes like the TEST13 one from @cheba - this will either fix the problem for good, or will give us much better crash reports on where the problem is occurring in the first place:

https://www.dropbox.com/s/jugpviv4l6vf63s/Trailer-TEST14.zip?dl=0

**Comment by ptsochantaris** [comment]
Still getting crashes when Trailer is left on a machine that sleeps overnight. Will investigate more - please do attach crash reports if you get any as well.

**Comment by ptsochantaris** [comment]
Updated test build including the cleanups above and perhaps more sanity related to the crashes:

https://www.dropbox.com/s/1qwe6m2l1lbvwpr/Trailer-TEST15.zip?dl=0

**Comment by cheba** [comment]
[Test **_14_** Crash report](http://cl.ly/0n0f2o0t2E1p) — not sure if it's of any use ATM. Just in case.

**Comment by ptsochantaris** [comment]
Quick note: Sorry for the slow updates, I have identified a few possible issues and there will be a new test build & commits over the weekend.

**Comment by ptsochantaris** [comment]
Test 16 now up - this should correct many of the crashes that have been occurring when Trailer runs on a laptop that goes to sleep. The issues seem to come from PowerNap specifically, and there is a cascade of faults that ends up tripping an ugly bug in the Swift runtime.  Additionally, this build features far more sane handling of sync failing for a specific API server, as well as improved status item and label handling in the overall sync.

https://www.dropbox.com/s/50q1tvjiv7a3zbq/Trailer-TEST16.zip?dl=0

Fingers crossed - hoping for a release in the next few days if there are no more crashes of this kind...

**Comment by mauricerkelly** [comment]
@ptsochantaris anything special to be done to clean up this version? I had been trying to run it from Xcode, then had also tried out the stable build. Now I can’t get anything to run. Have deleted `~/Library/Application\ Support/com.housetrip.Trailer` and `~/Library/Preferences/com.housetrip.Trailer.plist` but still nothing appears when the app is launched. No crash logs either.

Anything else to clean out?

**Comment by ptsochantaris** [comment]
@mauricerkelly Nothing else is written apart from that file and the support directory you mention, so what you describe should be a total reset.

What happens when you try to run the new version from Xcode? Do you get a debugger session with a stack trace perhaps?

**Comment by mauricerkelly** [comment]
@ptsochantaris dammit - had taken until this evening for me to find the time to test in Xcode. However this afternoon my machine died during a wake from sleep, and when I rebooted Trailer was working fine again!

**Comment by ptsochantaris** [comment]
Sounds like you may have had a "zombie" instance of Trailer already running in the background, that's why the new instance would not start - but I'm just guessing.

**Comment by cheba** [comment]
I'm running the latest build and it seem to have a problem. It doesn't crush but it sticks on refresh after (during?) sleep.

Here's what I've found in logs.
```
Jan 28 01:59:56 MacBook-Pro.local Trailer[51781]: Starting refresh
Jan 28 01:59:56 MacBook-Pro.local Trailer[51781]: Network went down: 0
Jan 28 01:59:57 MacBook-Pro.local Trailer[51781]: (GitHub) GET https:/api.github.com/user - FAILED: The operation couldn’t be completed. (NSURLErrorDomain error -1009.)
Jan 28 01:59:57 MacBook-Pro.local Trailer[51781]: (GitHub) failure for /user: The operation couldn’t be completed. (NSURLErrorDomain error -1009.)
Jan 28 09:10:49 MacBook-Pro.local Trailer[51781]: Network came up: 1
```

01:59 — MBP was (should have been) sleeping at that time.
09:10 — I woke it up about that time.

**Comment by ptsochantaris** [comment]
Yes, that's what was causing (or rather triggering the thing that caused) the crashes before. Basically it seems as if Power Nap is doing strange things to the network state while a device sleeps. In my logs sometimes I get full syncs completing while the system was supposed to be sleeping, sometimes I see a few aborted ones.  I think it has more to do with whether the system came up for a power-nap or came up for a second just to check-in with iCloud or the NAT router or something, as OS X sometimes does.

If you wait for a little while a refresh should run after that (interesting that it didn't run immediately after the network came back up, will look into this)

Let me know if you spot more of this, or if the refresh doesn't actually end up running after all!

**Comment by cheba** [comment]
This morning it was over 2 hours when I restarted Trailer and it didn't end syncing.

**Comment by ptsochantaris** [comment]
@cheba Can you enable logging to console and if this occurs again, i.e. syncing taking forever, could you provide a dump if possible?

Did sync work fine after Trailer was restarted?

**Comment by cheba** [comment]
Yes, it worked fine after restart.

Just enabled logging. Is dump a process sample or just all the logs?

**Comment by ptsochantaris** [comment]
@cheba Oh, basically, the logs from Trailer are fine - don't need the process info. Trailer currently writes to the system log (which may warrant it's own feature request later perhaps...) so you'd probably want to hunt and "see" where the sync got "stuck". It may even make more sense to describe it rather than attach a long log dump from your system of course.

**Comment by cheba** [comment]
Trailer's stuck again. Over two hours now.

Here's a [part of system.log](http://cl.ly/2j1X2T3P3j1N) relevant to this night's power nap. Though, it looks pretty useless. Trailer only logged a few lines. Maybe networking log around it would help you.

I couldn't find any other log files.

**Comment by ptsochantaris** [comment]
"Jan 29 02:14:52 MacBook-Pro.local Trailer[3945]: Network went down: 0"

Interesting, from your log it looks as if the network went down - is there any reference in the logs about the network coming back up?

Should contain the text "Network came up:" - can you provide logs around that time if that occurred?

**Comment by cheba** [comment]
That is the whole chunk for the night wake up.

No more entries until I woke up the computer in the morning.
> Jan 29 09:08:41 MacBook-Pro kernel[0]: AirPort_Brcm43xx::powerChange: System Wake - Full Wake/ Dark Wake / Maintenance wake
> Jan 29 09:08:41 MacBook-Pro kernel[0]: Previous sleep cause: 5
> Jan 29 09:08:41 MacBook-Pro kernel[0]: wlEvent: en1 en1 Link DOWN virtIf = 0
> Jan 29 09:08:41 MacBook-Pro kernel[0]: AirPort: Link Down on en1. Reason 8 (Disassociated because station leaving).
> Jan 29 09:08:41 MacBook-Pro kernel[0]: en1: link down event, informing supplicant.
> Jan 29 09:08:41 MacBook-Pro kernel[0]: en1: channel changed to 1
> Jan 29 09:08:41 MacBook-Pro kernel[0]: en1::IO80211Interface::postMessage bssid changed
> Jan 29 09:08:41 MacBook-Pro kernel[0]: en1: channel changed to 1
> Jan 29 09:08:41 MacBook-Pro kernel[0]: en1: setting diversity to: -1
> Jan 29 09:08:41 MacBook-Pro kernel[0]: en1: Error configuring antenna diversity (index = -1).
> Jan 29 09:08:41 MacBook-Pro kernel[0]: en1: setting tx antenna: -1
> Jan 29 09:08:41 MacBook-Pro.local configd[30]: network changed: v4(en1-:192.168.0.200) DNS- Proxy-
> Jan 29 09:08:41 MacBook-Pro.local networkd[239]: +[NETLedBelly stopFastFail] Clearing ledbelly failure cache
> Jan 29 09:08:41 MacBook-Pro kernel[0]: IO80211ScanManager::startScan: Broadcast scan request received from 'airportd' (pid 35) ().
> Jan 29 09:08:41 MacBook-Pro kernel[0]: IO80211ScanManager::startScan: Initiating scan.
> Jan 29 09:08:41 MacBook-Pro kernel[0]: en1: channel changed to 1
> Jan 29 09:08:41 MacBook-Pro kernel[0]: IO80211ScanManager::scanDone: Scheduling cache purge timer in 30 seconds.
> Jan 29 09:08:41 MacBook-Pro kernel[0]: IO80211ScanManager::getScanResult: All scan results returned for 'airportd' (pid 35).
> Jan 29 09:08:41 MacBook-Pro kernel[0]: en1: Terminating supplicant.
> Jan 29 09:08:41 MacBook-Pro kernel[0]: RSNSupplicant: Releasing authenticator for 00:1f:f3:c1:87:20
> Jan 29 09:08:41 MacBook-Pro kernel[0]: parseRSNIE: groupCipherType = 5 pairwiseCipherType = 5 authSel = 2
> Jan 29 09:08:41 MacBook-Pro kernel[0]: initWithInterfaceAndIE: _myMacAddress 34:15:9e:90:e3:29
> Jan 29 09:08:41 MacBook-Pro kernel[0]: setPMK: PMK SET!
> Jan 29 09:08:41 MacBook-Pro kernel[0]: MacAuthEvent en1   Auth result for: 00:1f:f3:c1:87:20  MAC AUTH succeeded
> Jan 29 09:08:41 MacBook-Pro kernel[0]: wlEvent: en1 en1 Link UP virtIf = 0
> Jan 29 09:08:41 MacBook-Pro kernel[0]: AirPort: Link Up on en1
> Jan 29 09:08:41 MacBook-Pro kernel[0]: en1: BSSID changed to 00:1f:f3:c1:87:20
> Jan 29 09:08:41 MacBook-Pro kernel[0]: en1: channel changed to 11
> Jan 29 09:08:41 MacBook-Pro kernel[0]: en1::IO80211Interface::postMessage bssid changed
> Jan 29 09:08:41 MacBook-Pro.local configd[30]: network changed: DNS* Proxy
> Jan 29 09:08:41 MacBook-Pro.local configd[30]: network changed: v4(en1!:192.168.0.200) DNS+ Proxy+ SMB
> Jan 29 09:08:42 MacBook-Pro kernel[0]: en1: BSSID changed to 00:1f:f3:c1:87:20
> Jan 29 09:08:42 MacBook-Pro kernel[0]: en1: channel changed to 11
> Jan 29 09:08:42 MacBook-Pro.local networkd[239]: +[NETLedBelly stopFastFail] Clearing ledbelly failure cache
> **Jan 29 09:08:48 MacBook-Pro.local Trailer[3945]: Network came up: 1**

The next entry from Trailer is this:
> Jan 29 11:27:16 MacBook-Pro.local Trailer[3945]: Updating menu, 15 total PRs

Note the 2h delay. No other related entries (except one from Sparkle).

UI is still locked in "Refreshing…".

**Comment by ptsochantaris** [comment]
Ah, this is useful info - actually Trailer's been doing the right thing up until that "network came up" line - that's fine. What's weird is that it seems Trailer thinks there is a refresh going on, that's why it's not kick-starting a new one when the network came back up. I did make some logic fixes related to that recently, so I'm guessing this is related. Will check out why this may be happening and tweak things, thanks!

**Comment by ptsochantaris** [comment]
Finally found the issue, a very well-hidden lack of a "()" in a closure call (see the fix commit above)  This build should correct the issue reported by @cheba - Thanks again for the reports, it would not have been found otherwise.

https://www.dropbox.com/s/ccxpz9a39g6ix0t/Trailer-TEST17.zip?dl=0

**Comment by cheba** [comment]
@ptsochantaris The last build seems to work fine. Didn't stuck two last nights.

**Comment by ptsochantaris** [comment]
That's great news - it seems quite stable on this end. We may finally be on the final approach for the 1.2 release!

**Comment by ptsochantaris** [comment]
Unless something comes up I'm going to merge this into the master branch tomorrow. @cheba and @mauricerkelly I really appreciate all the time you've put into testing this. I don't think we've found every issue, and I bet 1.2.1 will be following quickly, but thanks to your help we can release a 1.2.0 which is certainly good enough, considering that about 10k lines of code have been replaced :)

That said, please do continue reporting issues and suggestions in the "issues" section! :)

**Comment by mauricerkelly** [comment]
@ptsochantaris that’s awesome. I look forward to playing with the Swift code properly :-D
